In [1]:
from IPython.core.interactiveshell import InteractiveShell
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
%matplotlib inline 
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3

In [2]:
#Name of Excel xlsx file. SQLite database will have the same name and extension .db
filename="data/1Q19/IBNRSQLite" 
con=sqlite3.connect(filename+".db")
sheet_name="Ultimate-Table"
df1 = pd.read_excel('data/1Q19/IBNR.xlsx', sheet_name = sheet_name)
df1.to_sql(sheet_name,con, index=False, if_exists='replace')
con.commit()
# con.close()

In [16]:
# now lets take a query that we think should get the inner join data between the reinsurance, premium and loss data and export the data to ??

# sql_statement='''
# select r.PolicyNumber as rp, p.PolicyNumber as pp, l.PolicyNumber as lp
# from reinsurance as r
# join premium as p on p.PolicyNumber=r.PolicyNumber
# join loss as l on l.PolicyNumber=r.PolicyNumber
# '''

# sql_statement='''
# select u18.Year as Year18, u18.TR as TreatyYear, u18.Contract as Contract, u18.Coverage as Coverage18, u18.Indemnity as Indemnity18, u18.ALAE as ALAE18
# from "Ultimate-Table" as u18
# where u18.year='2018'
# '''

# sql_statement='''
# select curr.TR as TreatyYear, curr.Contract as Contract, curr.Coverage as Coverage, curr.Indemnity as Indemnity, curr.ALAE as ALAE, 
# 	currMinus1.Coverage as Coverage_P1, currMinus1.Indemnity as Indemnity_P1, currMinus1.ALAE as ALAE_P1
# from "Ultimate-Table" as curr
# left join "Ultimate-Table" as currMinus1 on currMinus1.TR=curr.TR and currMinus1.Contract=curr.Contract 
# --left join "Ultimate-Table" as currMinus2 on currMinus2.TR=curr.TR and currMinus2.Contract=curr.Contract 
# where curr.year='2018' \
# and currMinus1.Year='2017'
# --and currMinus2.Year='2016'
# '''

sql_statement='''
select curr.TR as TreatyYear, curr.Contract as Contract, curr.Coverage as Coverage18, curr.Indemnity as Indemnity18, curr.ALAE as ALAE18, 
	currMinus1.Coverage as Coverage17, currMinus1.Indemnity as Indemnity17, currMinus1.ALAE as ALAE17
from "Ultimate-Table" as curr
left join "Ultimate-Table" as currMinus1 on currMinus1.TR=curr.TR and currMinus1.Contract=curr.Contract 
--left join "Ultimate-Table" as currMinus2 on currMinus2.TR=curr.TR and currMinus2.Contract=curr.Contract 
where curr.year='2018' \
and currMinus1.Year='2017'
--and currMinus2.Year='2016'
'''

## this pulls the cooked/final report view into a dataframe
df_cooked_ultimate = pd.read_sql(sql_statement,con)
print("shape=%s" % str(df.shape))
df_cooked_ultimate

shape=(75, 8)

,TreatyYear,Contract,Coverage18,Indemnity18,ALAE18,Coverage17,Indemnity17,ALAE17
0,1982,First Excess,None,0.000000e+00,0.000000e+00,None,0.0,0.0
1,1983,First Excess,None,1.862238e+06,3.727570e+05,None,1862238.0,372757.0
2,1984,Second Excess,None,3.632908e+06,1.132560e+05,None,3632908.0,113256.0
3,1985,Clash,None,3.841498e+06,6.234100e+04,None,3841498.0,62341.0
4,1986,Clash,None,1.869000e+06,0.000000e+00,None,1869000.0,0.0
5,1987,Clash,None,0.000000e+00,0.000000e+00,None,0.0,0.0
6,1988,First Excess,None,2.400000e+06,3.483980e+05,None,2400000.0,348398.0
7,1988,Second Excess,None,0.000000e+00,0.000000e+00,None,0.0,0.0
8,1989,First Excess,None,2.062178e+06,2.450100e+05,None,2062178.0,245010.0
9,1989,Second Excess,None,0.000000e+00,0.000000e+00,None,0.0,0.0
10,1990,First Excess,None,4.942490e+06,3.713290e+05,None,4942490.0,371329.0
11,1994,Excess Pool,None,9.000000e+05,0.000000e+00,None,900000.0,NaN
12,1994,Codogno Facultative- Carbrini,None,1.053704e+07,3.908929e+06,None,10537043.0,3908929.0
13,1995,Excess Pool,None,1.632450e+06,0.000000e+00,None,1632450.0,0.0
14,1995,Fac. Hos / Reg Hos,None,0.000000e+00,0.000000e+00,None,0.0,0.0
15,1995,Podiatrists,None,1.399990e+05,4.054300e+04,None,139999.0,40543.0
16,1996,Podiatrists,None,0.000000e+00,0.000000e+00,None,NaN,NaN
17,1996,Excess Pool,None,6.048410e+06,0.000000e+00,None,6048410.0,0.0
18,1996,Codogno Facultative,None,0.000000e+00,0.000000e+00,None,0.0,0.0
19,1997,Excess Pool,None,4.100000e+06,0.000000e+00,None,4100000.0,0.0
20,1997,Codogno Facultative,None,0.000000e+00,0.000000e+00,None,0.0,0.0
21,1998,Codogno Facultative,None,0.000000e+00,0.000000e+00,None,0.0,0.0
22,1998,Excess Pool,None,6.775000e+06,0.000000e+00,None,6775000.0,0.0
23,1998,First Excess - phy,None,4.381850e+07,2.958925e+06,None,43818497.0,2958925.0
24,1998,First Excess - hos,None,1.038125e+07,5.727600e+05,None,10381250.0,572760.0
25,1998,First Excess - Pod,None,6.250000e+05,6.521400e+04,None,625000.0,65214.0
26,1999,Codogno Facultative,None,0.000000e+00,0.000000e+00,None,0.0,0.0
27,1999,Excess Pool,None,2.831250e+06,0.000000e+00,None,2831250.0,NaN
28,2000,Excess Pool,None,4.550000e+06,0.000000e+00,None,4550000.0,0.0
29,2001,Codogno Facultative,None,0.000000e+00,0.000000e+00,None,NaN,NaN
...,...,...,...,...,...,...,...,...
45,2007,Hospital Facultative - Brookhaven,None,0.000000e+00,0.000000e+00,None,NaN,NaN
46,2007,Hospital Facultative - Public Health Solutions,None,NaN,NaN,None,NaN,NaN
47,2007,PaPRI retrocession,None,8.164400e+05,5.314220e+05,None,816440.0,531422.0
48,2007,PaPRI retrocession,None,8.164400e+05,5.314220e+05,Temp,NaN,NaN
49,2008,Hospital Facultative - Brookhaven,None,NaN,NaN,None,NaN,NaN
50,2008,Hospital Facultative-Medical Health and Research,None,NaN,NaN,None,NaN,NaN
51,2009,Hospital Facultative - Public Health Solutions,None,NaN,NaN,None,NaN,NaN
52,2009,Clash,"7,000 xs 3,000",5.050048e+06,2.657920e+05,"7,000 xs 3,000",5050920.0,265838.0
53,2010,Clash,"7,000 xs 3,000",2.957113e+06,1.556375e+05,"7,000 xs 3,000",2923823.0,153885.0
54,2011,Clash,"7,000 xs 3,000",9.478127e+06,4.988488e+05,"7,000 xs 3,000",8000099.0,421058.0
55,2012,Clash,"6,700 xs 3,300",2.239597e+06,1.178735e+05,"6,700 xs 3,300",2781680.0,146404.0
56,2013,Clash,"6,700 xs 3,300",2.479754e+06,1.305134e+05,"6,700 xs 3,300",5187528.0,273028.0
57,2014,Clash,"6,700 xs 3,300",2.787680e+06,1.200573e+05,"6,700 xs 3,300",3276841.0,145800.0
58,2015,Clash,"4,700 xs 3,300",3.546113e+06,1.490411e+05,"4,700 xs 3,300",7274309.0,345262.0
59,2016,Clash,"4,700 xs 3,300",2.141317e+06,9.625021e+04,"4,700 xs 3,300",2141317.0,96250.0
60,2017,Clash,"4,700 xs 3,300",1.884528e+06,9.119505e+04,"4,700 xs 3,300",1884528.0,91195.0
61,2018,Clash,"4,700 xs 3,300",1.051754e+06,2.629385e+05,"4,700 xs 3,300",NaN,NaN
62,2011,HCF XOL,"1,000 xs 1,000",4.900000e+05,2.312100e+04,"1,000 xs 1,000",1190000.0,49371.0
63,2014,NSPC,"1st 500,000",1.467873e+06,3.669682e+05,"1st 500,000",1519893.0,379973.0
64,2015,NSPC,"1st 500,000",1.915539e+06,4.788848e+05,"1st 500,000",2315792.0,578948.0
65,2016,NSPC,"1st 500,000",2.316829e+06,5.792072e+05,"1st 500,000",2559946.0,639986.0
66,2017,NSPC,"1st 500,000",1.813640e+06,4.534100e+05,"1st 500,000",1057277.0,264319.0
67,2018,NSPC,"1st 500,000",1.200000e+06,3.000000e+05,"1st 500,000",NaN,NaN
68,2007,PaPRI retrocession,Temp,NaN,NaN,None,816440.0,531422.0
69,2007,PaPRI retrocession,Temp,NaN,NaN,Temp,NaN,NaN
70,2015,Per Risk Excess,"1,500/800 xs 500",1.483628e+06,0.000000e+00,"1,500/800 xs 500",1483628.0,NaN
71,2016,Per Risk Excess,"1,500/800 xs 500",8.748740e+05,0.000000e+00,"1,500/800 xs 500",874874.0,NaN
72,2017,Per Risk Excess,"1,500/800 xs 500",1.730957e+06,0.000000e+00,"1,500/800 xs 500",987711.0,NaN
73,2018,Per Risk Excess,"1,500/800 xs 500",1.384071e+06,0.000000e+00,"1,500/800 xs 500",NaN,NaN
74,2018,Commutation Adjustment - Excess,None,2.100000e+07,NaN,None,21000000.0,NaN

In [17]:
## now its time to store the cooked dataframe to a table
df_cooked_ultimate.to_sql("Ultimate-Cooked-Report",con, index=False, if_exists='replace')
con.commit()

## also - lets save it to excel
df_cooked_ultimate.to_excel('data/1Q19/ultimate-cooked.xlsx')